# baseurl = "https://hereispaul.com"
baseurl = "https://cs.stanford.edu/people/paulliu"
languageCode = "en-us"
copyright = "Procrastinating since '92."
MetaDataFormat = "toml"
title = "Paul Liu | Stanford"
assetDir = "assets"

[params]
    name = "Paul Liu"
	description  = "Paul Liu | Stanford"

# [indexes]
#     tag = "tags"
#     topic = "topics"

